crystal_structure:
  lattice_parameters:
    a: 5.981
    b: 10.354
    c: 6.014
    alpha: 90
    beta: 108.8
    gamma: 90
  atoms_uc:
  - label: Ru0
    pos:
    - 0.0
    - 0.3333
    - 0.0
    spin_S: 0.5
  - label: Ru1
    pos:
    - 0.0
    - 0.6667000000000001
    - 0.0
    spin_S: 0.5
  - label: Ru2
    pos:
    - 0.5
    - 0.8332999999999999
    - 0.0
    spin_S: 0.5
  - label: Ru3
    pos:
    - 0.5
    - 0.16670000000000001
    - 0.0
    spin_S: 0.5
  magnetic_elements:
  - Ru
  dimensionality: 3
interactions: []
magnetic_structure:
  enabled: false
  type: pattern
  pattern_type: antiferromagnetic
  directions: []
  QVector:
  - 0
  - 1
  - 0.5
  Spins:
    Ru:
    - 0.8
    - 0
    - 0.6
parameters:
  H_dir:
  - 0.0
  - 0.0
  - 1.0
  H_mag: 0.0
tasks:
  minimization: false
  dispersion: true
  sqw_map: true
  export_csv: false
q_path:
  Start:
  - 0
  - 0
  - 0
  End:
  - 0.5
  - 0.5
  - 0
  Gamma:
  - 0
  - 0
  - 0
  M:
  - 0
  - 0.5
  - 0
  K:
  - 0.3333
  - 0.3333
  - 0
  path:
  - Gamma
  - M
  - K
  - Gamma
  points_per_segment: 50
minimization:
  enabled: false
  num_starts: 1000
  n_workers: 8
  early_stopping: 10
  method: L-BFGS-B
plotting:
  energy_min: 0
  energy_max: 20
  broadening: 0.2
  energy_resolution: 0.05
  momentum_max: 4
  save_plot: true
  disp_plot_filename: disp_plot.png
  sqw_plot_filename: sqw_plot.png
  show_plot: true
  plot_structure: true
  energy_limits_disp:
  - 0
  - 20
  broadening_width: 0.2
calculation:
  cache_mode: none
output:
  export_csv: false
