crystal_structure:
  lattice_parameters:
    a: 20.645
    b: 8.383
    c: 6.442
    alpha: 90
    beta: 90
    gamma: 90
  atoms_uc:
    - label: Cu0
      pos: [0.16572, 0.3646, 0.7545]
      spin_S: 0.5
      species: Cu0
    - label: Cu1
      pos: [0.83428, 0.6354, 0.7545]
      spin_S: 0.5
      species: Cu1
    - label: Cu2
      pos: [0.16572, 0.8646, 0.2545]
      spin_S: 0.5
      species: Cu2
    - label: Cu3
      pos: [0.83428, 0.1354, 0.2545]
      spin_S: 0.5
      species: Cu3
    - label: Cu4
      pos: [0.66572, 0.3646, 0.2545]
      spin_S: 0.5
      species: Cu4
    - label: Cu5
      pos: [0.33428, 0.6354, 0.2545]
      spin_S: 0.5
      species: Cu5
    - label: Cu6
      pos: [0.66572, 0.8646, 0.7545]
      spin_S: 0.5
      species: Cu6
    - label: Cu7
      pos: [0.33428, 0.1354, 0.7545]
      spin_S: 0.5
      species: Cu7
    - label: Cu8
      pos: [0.41572, 0.8854, 1.0045]
      spin_S: 0.5
      species: Cu8
    - label: Cu9
      pos: [0.08428, 0.6146, 1.0045]
      spin_S: 0.5
      species: Cu9
    - label: Cu10
      pos: [0.41572, 0.3854, 0.5045]
      spin_S: 0.5
      species: Cu10
    - label: Cu11
      pos: [0.08428, 1.1146, 0.5045]
      spin_S: 0.5
      species: Cu11
    - label: Cu12
      pos: [0.91572, 0.8854, 0.5045]
      spin_S: 0.5
      species: Cu12
    - label: Cu13
      pos: [0.58428, 0.6146, 0.5045]
      spin_S: 0.5
      species: Cu13
    - label: Cu14
      pos: [0.91572, 0.3854, 1.0045]
      spin_S: 0.5
      species: Cu14
    - label: Cu15
      pos: [0.58428, 0.1146, 1.0045]
      spin_S: 0.5
      species: Cu15
  magnetic_elements:
    - Cu
  dimensionality: 3
interactions:
  - type: heisenberg
    pair: [Cu0, Cu5]
    distance: 5.2572
    value: J3
    atom_i: 0
    atom_j: 5
  - type: heisenberg
    pair: [Cu0, Cu7]
    distance: 3.9751
    value: J2
    atom_i: 0
    atom_j: 7
  - type: heisenberg
    pair: [Cu0, Cu9]
    distance: 3.1325
    value: J1
    atom_i: 0
    atom_j: 9
  - type: anisotropic_exchange
    pair: [Cu0, Cu9]
    distance: 3.1325
    value: [G1, '-G1', '-G1']
    atom_i: 0
    atom_j: 9
  - type: dm_manual
    atom_i: 0
    atom_j: 9
    offset_j: [0, 0, 0]
    value: [-2.67, 0, 0]
  - type: heisenberg
    pair: [Cu0, Cu11]
    distance: 3.1325
    value: J1
    atom_i: 0
    atom_j: 11
  - type: anisotropic_exchange
    pair: [Cu0, Cu11]
    distance: 3.1325
    value: [G1, '-G1', '-G1']
    atom_i: 0
    atom_j: 11
  - type: dm_manual
    atom_i: 0
    atom_j: 11
    offset_j: [0, -1, 0]
    value: [2.67, 0, 0]
  - type: heisenberg
    pair: [Cu1, Cu4]
    distance: 5.2572
    value: J3
    atom_i: 1
    atom_j: 4
  - type: heisenberg
    pair: [Cu1, Cu6]
    distance: 3.9751
    value: J2
    atom_i: 1
    atom_j: 6
  - type: heisenberg
    pair: [Cu1, Cu12]
    distance: 3.1325
    value: J1
    atom_i: 1
    atom_j: 12
  - type: anisotropic_exchange
    pair: [Cu1, Cu12]
    distance: 3.1325
    value: [G1, '-G1', '-G1']
    atom_i: 1
    atom_j: 12
  - type: dm_manual
    atom_i: 1
    atom_j: 12
    offset_j: [0, 0, 0]
    value: [-2.67, 0, 0]
  - type: heisenberg
    pair: [Cu1, Cu14]
    distance: 3.1325
    value: J1
    atom_i: 1
    atom_j: 14
  - type: anisotropic_exchange
    pair: [Cu1, Cu14]
    distance: 3.1325
    value: [G1, '-G1', '-G1']
    atom_i: 1
    atom_j: 14
  - type: dm_manual
    atom_i: 1
    atom_j: 14
    offset_j: [0, 0, 0]
    value: [2.67, 0, 0]
  - type: heisenberg
    pair: [Cu2, Cu5]
    distance: 3.9751
    value: J2
    atom_i: 2
    atom_j: 5
  - type: heisenberg
    pair: [Cu2, Cu11]
    distance: 3.1325
    value: J1
    atom_i: 2
    atom_j: 11
  - type: anisotropic_exchange
    pair: [Cu2, Cu11]
    distance: 3.1325
    value: [G1, '-G1', '-G1']
    atom_i: 2
    atom_j: 11
  - type: dm_manual
    atom_i: 2
    atom_j: 11
    offset_j: [0, 0, 0]
    value: [-2.67, 0, 0]
  - type: heisenberg
    pair: [Cu2, Cu9]
    distance: 3.1325
    value: J1
    atom_i: 2
    atom_j: 9
  - type: anisotropic_exchange
    pair: [Cu2, Cu9]
    distance: 3.1325
    value: [G1, '-G1', '-G1']
    atom_i: 2
    atom_j: 9
  - type: dm_manual
    atom_i: 2
    atom_j: 9
    offset_j: [0, 0, -1]
    value: [2.67, 0, 0]
  - type: heisenberg
    pair: [Cu2, Cu7]
    distance: 5.2572
    value: J3
    atom_i: 2
    atom_j: 7
  - type: heisenberg
    pair: [Cu3, Cu4]
    distance: 3.9751
    value: J2
    atom_i: 3
    atom_j: 4
  - type: heisenberg
    pair: [Cu3, Cu6]
    distance: 5.2572
    value: J3
    atom_i: 3
    atom_j: 6
  - type: heisenberg
    pair: [Cu3, Cu12]
    distance: 3.1325
    value: J1
    atom_i: 3
    atom_j: 12
  - type: anisotropic_exchange
    pair: [Cu3, Cu12]
    distance: 3.1325
    value: [G1, '-G1', '-G1']
    atom_i: 3
    atom_j: 12
  - type: dm_manual
    atom_i: 3
    atom_j: 12
    offset_j: [0, -1, 0]
    value: [2.67, 0, 0]
  - type: heisenberg
    pair: [Cu3, Cu14]
    distance: 3.1325
    value: J1
    atom_i: 3
    atom_j: 14
  - type: anisotropic_exchange
    pair: [Cu3, Cu14]
    distance: 3.1325
    value: [G1, '-G1', '-G1']
    atom_i: 3
    atom_j: 14
  - type: dm_manual
    atom_i: 3
    atom_j: 14
    offset_j: [0, 0, -1]
    value: [-2.67, 0, 0]
  - type: heisenberg
    pair: [Cu4, Cu1]
    distance: 5.2572
    value: J3
    atom_i: 4
    atom_j: 1
  - type: heisenberg
    pair: [Cu4, Cu3]
    distance: 3.9751
    value: J2
    atom_i: 4
    atom_j: 3
  - type: heisenberg
    pair: [Cu4, Cu13]
    distance: 3.1325
    value: J1
    atom_i: 4
    atom_j: 13
  - type: anisotropic_exchange
    pair: [Cu4, Cu13]
    distance: 3.1325
    value: [G1, '-G1', '-G1']
    atom_i: 4
    atom_j: 13
  - type: dm_manual
    atom_i: 4
    atom_j: 13
    offset_j: [0, 0, 0]
    value: [-2.67, 0, 0]
  - type: heisenberg
    pair: [Cu4, Cu15]
    distance: 3.1325
    value: J1
    atom_i: 4
    atom_j: 15
  - type: anisotropic_exchange
    pair: [Cu4, Cu15]
    distance: 3.1325
    value: [G1, '-G1', '-G1']
    atom_i: 4
    atom_j: 15
  - type: dm_manual
    atom_i: 4
    atom_j: 15
    offset_j: [0, 0, -1]
    value: [2.67, 0, 0]
  - type: heisenberg
    pair: [Cu5, Cu0]
    distance: 5.2572
    value: J3
    atom_i: 5
    atom_j: 0
  - type: heisenberg
    pair: [Cu5, Cu2]
    distance: 3.9751
    value: J2
    atom_i: 5
    atom_j: 2
  - type: heisenberg
    pair: [Cu5, Cu10]
    distance: 3.1325
    value: J1
    atom_i: 5
    atom_j: 10
  - type: anisotropic_exchange
    pair: [Cu5, Cu10]
    distance: 3.1325
    value: [G1, '-G1', '-G1']
    atom_i: 5
    atom_j: 10
  - type: dm_manual
    atom_i: 5
    atom_j: 10
    offset_j: [0, 0, 0]
    value: [2.67, 0, 0]
  - type: heisenberg
    pair: [Cu5, Cu8]
    distance: 3.1325
    value: J1
    atom_i: 5
    atom_j: 8
  - type: anisotropic_exchange
    pair: [Cu5, Cu8]
    distance: 3.1325
    value: [G1, '-G1', '-G1']
    atom_i: 5
    atom_j: 8
  - type: dm_manual
    atom_i: 5
    atom_j: 8
    offset_j: [0, 0, -1]
    value: [-2.67, 0, 0]
  - type: heisenberg
    pair: [Cu6, Cu1]
    distance: 3.9751
    value: J2
    atom_i: 6
    atom_j: 1
  - type: heisenberg
    pair: [Cu6, Cu13]
    distance: 3.1325
    value: J1
    atom_i: 6
    atom_j: 13
  - type: anisotropic_exchange
    pair: [Cu6, Cu13]
    distance: 3.1325
    value: [G1, '-G1', '-G1']
    atom_i: 6
    atom_j: 13
  - type: dm_manual
    atom_i: 6
    atom_j: 13
    offset_j: [0, 0, 0]
    value: [2.67, 0, 0]
  - type: heisenberg
    pair: [Cu6, Cu3]
    distance: 5.2572
    value: J3
    atom_i: 6
    atom_j: 3
  - type: heisenberg
    pair: [Cu6, Cu15]
    distance: 3.1325
    value: J1
    atom_i: 6
    atom_j: 15
  - type: anisotropic_exchange
    pair: [Cu6, Cu15]
    distance: 3.1325
    value: [G1, '-G1', '-G1']
    atom_i: 6
    atom_j: 15
  - type: dm_manual
    atom_i: 6
    atom_j: 15
    offset_j: [0, 1, 0]
    value: [-2.67, 0, 0]
  - type: heisenberg
    pair: [Cu7, Cu0]
    distance: 3.9751
    value: J2
    atom_i: 7
    atom_j: 0
  - type: heisenberg
    pair: [Cu7, Cu10]
    distance: 3.1325
    value: J1
    atom_i: 7
    atom_j: 10
  - type: anisotropic_exchange
    pair: [Cu7, Cu10]
    distance: 3.1325
    value: [G1, '-G1', '-G1']
    atom_i: 7
    atom_j: 10
  - type: dm_manual
    atom_i: 7
    atom_j: 10
    offset_j: [0, 0, 0]
    value: [-2.67, 0, 0]
  - type: heisenberg
    pair: [Cu7, Cu2]
    distance: 5.2572
    value: J3
    atom_i: 7
    atom_j: 2
  - type: heisenberg
    pair: [Cu7, Cu8]
    distance: 3.1325
    value: J1
    atom_i: 7
    atom_j: 8
  - type: anisotropic_exchange
    pair: [Cu7, Cu8]
    distance: 3.1325
    value: [G1, '-G1', '-G1']
    atom_i: 7
    atom_j: 8
  - type: dm_manual
    atom_i: 7
    atom_j: 8
    offset_j: [0, -1, 0]
    value: [2.67, 0, 0]
  - type: heisenberg
    pair: [Cu8, Cu13]
    distance: 5.2572
    value: J3
    atom_i: 8
    atom_j: 13
  - type: heisenberg
    pair: [Cu8, Cu5]
    distance: 3.1325
    value: J1
    atom_i: 8
    atom_j: 5
  - type: anisotropic_exchange
    pair: [Cu8, Cu5]
    distance: 3.1325
    value: [G1, '-G1', '-G1']
    atom_i: 8
    atom_j: 5
  - type: dm_manual
    atom_i: 8
    atom_j: 5
    offset_j: [0, 0, 1]
    value: [2.67, 0, 0]
  - type: heisenberg
    pair: [Cu8, Cu7]
    distance: 3.1325
    value: J1
    atom_i: 8
    atom_j: 7
  - type: anisotropic_exchange
    pair: [Cu8, Cu7]
    distance: 3.1325
    value: [G1, '-G1', '-G1']
    atom_i: 8
    atom_j: 7
  - type: dm_manual
    atom_i: 8
    atom_j: 7
    offset_j: [0, 1, 0]
    value: [-2.67, 0, 0]
  - type: heisenberg
    pair: [Cu8, Cu15]
    distance: 3.9751
    value: J2
    atom_i: 8
    atom_j: 15
  - type: heisenberg
    pair: [Cu9, Cu0]
    distance: 3.1325
    value: J1
    atom_i: 9
    atom_j: 0
  - type: anisotropic_exchange
    pair: [Cu9, Cu0]
    distance: 3.1325
    value: [G1, '-G1', '-G1']
    atom_i: 9
    atom_j: 0
  - type: dm_manual
    atom_i: 9
    atom_j: 0
    offset_j: [0, 0, 0]
    value: [2.67, 0, 0]
  - type: heisenberg
    pair: [Cu9, Cu12]
    distance: 5.2572
    value: J3
    atom_i: 9
    atom_j: 12
  - type: heisenberg
    pair: [Cu9, Cu14]
    distance: 3.9751
    value: J2
    atom_i: 9
    atom_j: 14
  - type: heisenberg
    pair: [Cu9, Cu2]
    distance: 3.1325
    value: J1
    atom_i: 9
    atom_j: 2
  - type: anisotropic_exchange
    pair: [Cu9, Cu2]
    distance: 3.1325
    value: [G1, '-G1', '-G1']
    atom_i: 9
    atom_j: 2
  - type: dm_manual
    atom_i: 9
    atom_j: 2
    offset_j: [0, 0, 1]
    value: [-2.67, 0, 0]
  - type: heisenberg
    pair: [Cu10, Cu5]
    distance: 3.1325
    value: J1
    atom_i: 10
    atom_j: 5
  - type: anisotropic_exchange
    pair: [Cu10, Cu5]
    distance: 3.1325
    value: [G1, '-G1', '-G1']
    atom_i: 10
    atom_j: 5
  - type: dm_manual
    atom_i: 10
    atom_j: 5
    offset_j: [0, 0, 0]
    value: [-2.67, 0, 0]
  - type: heisenberg
    pair: [Cu10, Cu7]
    distance: 3.1325
    value: J1
    atom_i: 10
    atom_j: 7
  - type: anisotropic_exchange
    pair: [Cu10, Cu7]
    distance: 3.1325
    value: [G1, '-G1', '-G1']
    atom_i: 10
    atom_j: 7
  - type: dm_manual
    atom_i: 10
    atom_j: 7
    offset_j: [0, 0, 0]
    value: [2.67, 0, 0]
  - type: heisenberg
    pair: [Cu10, Cu13]
    distance: 3.9751
    value: J2
    atom_i: 10
    atom_j: 13
  - type: heisenberg
    pair: [Cu10, Cu15]
    distance: 5.2572
    value: J3
    atom_i: 10
    atom_j: 15
  - type: heisenberg
    pair: [Cu11, Cu2]
    distance: 3.1325
    value: J1
    atom_i: 11
    atom_j: 2
  - type: anisotropic_exchange
    pair: [Cu11, Cu2]
    distance: 3.1325
    value: [G1, '-G1', '-G1']
    atom_i: 11
    atom_j: 2
  - type: dm_manual
    atom_i: 11
    atom_j: 2
    offset_j: [0, 0, 0]
    value: [2.67, 0, 0]
  - type: heisenberg
    pair: [Cu11, Cu12]
    distance: 3.9751
    value: J2
    atom_i: 11
    atom_j: 12
  - type: heisenberg
    pair: [Cu11, Cu14]
    distance: 5.2572
    value: J3
    atom_i: 11
    atom_j: 14
  - type: heisenberg
    pair: [Cu11, Cu0]
    distance: 3.1325
    value: J1
    atom_i: 11
    atom_j: 0
  - type: anisotropic_exchange
    pair: [Cu11, Cu0]
    distance: 3.1325
    value: [G1, '-G1', '-G1']
    atom_i: 11
    atom_j: 0
  - type: dm_manual
    atom_i: 11
    atom_j: 0
    offset_j: [0, 1, 0]
    value: [-2.67, 0, 0]
  - type: heisenberg
    pair: [Cu12, Cu1]
    distance: 3.1325
    value: J1
    atom_i: 12
    atom_j: 1
  - type: anisotropic_exchange
    pair: [Cu12, Cu1]
    distance: 3.1325
    value: [G1, '-G1', '-G1']
    atom_i: 12
    atom_j: 1
  - type: dm_manual
    atom_i: 12
    atom_j: 1
    offset_j: [0, 0, 0]
    value: [2.67, 0, 0]
  - type: heisenberg
    pair: [Cu12, Cu3]
    distance: 3.1325
    value: J1
    atom_i: 12
    atom_j: 3
  - type: anisotropic_exchange
    pair: [Cu12, Cu3]
    distance: 3.1325
    value: [G1, '-G1', '-G1']
    atom_i: 12
    atom_j: 3
  - type: dm_manual
    atom_i: 12
    atom_j: 3
    offset_j: [0, 1, 0]
    value: [-2.67, 0, 0]
  - type: heisenberg
    pair: [Cu12, Cu9]
    distance: 5.2572
    value: J3
    atom_i: 12
    atom_j: 9
  - type: heisenberg
    pair: [Cu12, Cu11]
    distance: 3.9751
    value: J2
    atom_i: 12
    atom_j: 11
  - type: heisenberg
    pair: [Cu13, Cu4]
    distance: 3.1325
    value: J1
    atom_i: 13
    atom_j: 4
  - type: anisotropic_exchange
    pair: [Cu13, Cu4]
    distance: 3.1325
    value: [G1, '-G1', '-G1']
    atom_i: 13
    atom_j: 4
  - type: dm_manual
    atom_i: 13
    atom_j: 4
    offset_j: [0, 0, 0]
    value: [2.67, 0, 0]
  - type: heisenberg
    pair: [Cu13, Cu6]
    distance: 3.1325
    value: J1
    atom_i: 13
    atom_j: 6
  - type: anisotropic_exchange
    pair: [Cu13, Cu6]
    distance: 3.1325
    value: [G1, '-G1', '-G1']
    atom_i: 13
    atom_j: 6
  - type: dm_manual
    atom_i: 13
    atom_j: 6
    offset_j: [0, 0, 0]
    value: [-2.67, 0, 0]
  - type: heisenberg
    pair: [Cu13, Cu8]
    distance: 5.2572
    value: J3
    atom_i: 13
    atom_j: 8
  - type: heisenberg
    pair: [Cu13, Cu10]
    distance: 3.9751
    value: J2
    atom_i: 13
    atom_j: 10
  - type: heisenberg
    pair: [Cu14, Cu1]
    distance: 3.1325
    value: J1
    atom_i: 14
    atom_j: 1
  - type: anisotropic_exchange
    pair: [Cu14, Cu1]
    distance: 3.1325
    value: [G1, '-G1', '-G1']
    atom_i: 14
    atom_j: 1
  - type: dm_manual
    atom_i: 14
    atom_j: 1
    offset_j: [0, 0, 0]
    value: [-2.67, 0, 0]
  - type: heisenberg
    pair: [Cu14, Cu3]
    distance: 3.1325
    value: J1
    atom_i: 14
    atom_j: 3
  - type: anisotropic_exchange
    pair: [Cu14, Cu3]
    distance: 3.1325
    value: [G1, '-G1', '-G1']
    atom_i: 14
    atom_j: 3
  - type: dm_manual
    atom_i: 14
    atom_j: 3
    offset_j: [0, 0, 1]
    value: [2.67, 0, 0]
  - type: heisenberg
    pair: [Cu14, Cu11]
    distance: 5.2572
    value: J3
    atom_i: 14
    atom_j: 11
  - type: heisenberg
    pair: [Cu14, Cu9]
    distance: 3.9751
    value: J2
    atom_i: 14
    atom_j: 9
  - type: heisenberg
    pair: [Cu15, Cu10]
    distance: 5.2572
    value: J3
    atom_i: 15
    atom_j: 10
  - type: heisenberg
    pair: [Cu15, Cu6]
    distance: 3.1325
    value: J1
    atom_i: 15
    atom_j: 6
  - type: anisotropic_exchange
    pair: [Cu15, Cu6]
    distance: 3.1325
    value: [G1, '-G1', '-G1']
    atom_i: 15
    atom_j: 6
  - type: dm_manual
    atom_i: 15
    atom_j: 6
    offset_j: [0, -1, 0]
    value: [2.67, 0, 0]
  - type: heisenberg
    pair: [Cu15, Cu8]
    distance: 3.9751
    value: J2
    atom_i: 15
    atom_j: 8
  - type: heisenberg
    pair: [Cu15, Cu4]
    distance: 3.1325
    value: J1
    atom_i: 15
    atom_j: 4
  - type: anisotropic_exchange
    pair: [Cu15, Cu4]
    distance: 3.1325
    value: [G1, '-G1', '-G1']
    atom_i: 15
    atom_j: 4
  - type: dm_manual
    atom_i: 15
    atom_j: 4
    offset_j: [0, 0, 1]
    value: [-2.67, 0, 0]
parameters:
  J1: 2.49
  J2: 2.7888000000000006
  J3: 5.0546999999999995
  G1: 0.28
  Dx: 2.67
  H_dir: [1, 0, 0]
  H_mag: 6
tasks:
  minimization: true
  dispersion: true
  sqw_map: true
  export_csv: false
q_path:
  Start: [0, 1, 0]
  End: [0, 3, 0]
  path: [Start, End]
  points_per_segment: 200
minimization:
  enabled: true
  num_starts: 1000
  n_workers: 8
  early_stopping: 10
  method: L-BFGS-B
plotting:
  energy_min: 0
  energy_max: 20
  broadening: 0.2
  energy_resolution: 0.05
  momentum_max: 4
  save_plot: false
  disp_plot_filename: CVO_propagation_disp.png
  sqw_plot_filename: CVO_propagation_sqw.png
  show_plot: false
  plot_structure: false
  energy_limits_disp: [0, 20]
  energy_limits_sqw: [0, 10]
  disp_title: aCVO Dispersion (Propagation Config)
  sqw_title: aCVO S(Q,w) (Propagatioin Config)
  broadening_width: 0.2
calculation:
  cache_mode: none
output:
  disp_data_filename: disp_data.npz
  sqw_data_filename: sqw_data.npz
  disp_csv_filename: disp_data.csv
  sqw_csv_filename: sqw_data.csv
  save_data: false
