crystal_structure:
  lattice_parameters:
    a: 20.645
    b: 8.383
    c: 6.442
    alpha: 90
    beta: 90
    gamma: 90
    space_group: 43
    dimensionality: 3D
  wyckoff_atoms:
    - label: Cu
      pos: [0.16572, 0.3646, 0.7545]
      spin_S: 0.5
  atom_mode: symmetry
  magnetic_elements:
    - Cu
  dimensionality: 3
interactions:
  symmetry_rules:
    - type: heisenberg
      distance: 3.1325301030013164
      value: J1
      ref_pair: [Cu0, Cu2]
      offset: [0, 0, 0]
    - type: dm
      distance: 3.1325301030013164
      value: Dx,0,0
      ref_pair: [Cu0, Cu2]
      offset: [0, 0, 0]
    - type: anisotropic_exchange
      distance: 3.1325301030013164
      value: G1,-G1,-G1
      ref_pair: [Cu0, Cu2]
      offset: [0, 0, 0]
    - type: heisenberg
      distance: 3.9751184254759506
      value: J2
      ref_pair: [Cu0, Cu13]
      offset: [0, 0, 0]
    - type: heisenberg
      distance: 5.257197069518927
      value: J3
      ref_pair: [Cu0, Cu9]
      offset: [0, 0, 0]
parameters:
  S: 1
  H_mag: 20
  H_dir: [0, 0, 1]
  J1: 2.49
  J2: 2.7888000000000006
  J3: 5.0546999999999995
  G1: 0.28
  Dx: 2.67
tasks:
  minimization: true
  dispersion: true
  sqw_map: true
  export_csv: false
q_path:
  Start: [0, 1, 0]
  End: [0, 3, 0]
  path: [Start, End]
  points_per_segment: 200
plotting:
  energy_min: 0
  energy_max: 10
  broadening: 0.2
  energy_resolution: 0.05
  momentum_max: 4
  save_plot: false
  disp_plot_filename: CVO_designer_disp.png
  sqw_plot_filename: CVO_designer_sqw.png
  show_plot: false
  plot_structure: false
  energy_limits_disp: [0, 10]
  energy_limits_sqw: [0, 10]
  disp_title: aCVO Dispersion (Designer Config)
  sqw_title: aCVO S(Q,w) (Designer Config)
  broadening_width: 0.2
minimization:
  enabled: true
  num_starts: 1000
  n_workers: 8
  early_stopping: 10
  method: L-BFGS-B
output:
  disp_data_filename: disp_data.npz
  sqw_data_filename: sqw_data.npz
  disp_csv_filename: disp_data.csv
  sqw_csv_filename: sqw_data.csv
  save_data: false
