crystal_structure:
  lattice_vectors:
    - - 7.33
      - 0
      - 0
    - - -3.6649999999999987
      - 6.347966209739936
      - 0
    - - 1.0493631027853925e-15
      - 1.8175502096124213e-15
      - 17.1374
  atoms_uc:
    - label: Fe0
      pos:
        - 0
        - 0
        - 0
      spin_S: 2.5
      species: Fe0
    - label: Fe1
      pos:
        - 0.5
        - 0
        - 0
      spin_S: 2.5
      species: Fe1
    - label: Fe2
      pos:
        - 0
        - 0.5
        - 0
      spin_S: 2.5
      species: Fe2
  dimensionality: 2
interactions:
  - type: heisenberg
    distance: 3.665
    value: J1
  - type: heisenberg
    distance: 6.348
    value: J2
  - type: dm_manual
    atom_i: 0
    atom_j: 1
    offset_j:
      - 0
      - 0
      - 0
    value:
      - '0'
      - '-Dy'
      - '-Dz'
    distance: 3.665
  - type: dm_manual
    atom_i: 0
    atom_j: 2
    offset_j:
      - 0
      - 0
      - 0
    value:
      - '-0.86602540378*Dy'
      - '-0.5*Dy'
      - Dz
    distance: 3.665
  - type: dm_manual
    atom_i: 0
    atom_j: 1
    offset_j:
      - -1
      - 0
      - 0
    value:
      - '0'
      - '-Dy'
      - '-Dz'
    distance: 3.665
  - type: dm_manual
    atom_i: 0
    atom_j: 2
    offset_j:
      - 0
      - -1
      - 0
    value:
      - '-0.86602540378*Dy'
      - '-0.5*Dy'
      - Dz
    distance: 3.665
  - type: dm_manual
    atom_i: 1
    atom_j: 0
    offset_j:
      - 0
      - 0
      - 0
    value:
      - '0'
      - Dy
      - Dz
    distance: 3.665
  - type: dm_manual
    atom_i: 1
    atom_j: 2
    offset_j:
      - 0
      - -1
      - 0
    value:
      - '-0.86602540378*Dy'
      - 0.5*Dy
      - '-Dz'
    distance: 3.665
  - type: dm_manual
    atom_i: 1
    atom_j: 0
    offset_j:
      - 1
      - 0
      - 0
    value:
      - '0'
      - Dy
      - Dz
    distance: 3.665
  - type: dm_manual
    atom_i: 1
    atom_j: 2
    offset_j:
      - 1
      - 0
      - 0
    value:
      - '-0.86602540378*Dy'
      - 0.5*Dy
      - '-Dz'
    distance: 3.665
  - type: dm_manual
    atom_i: 2
    atom_j: 0
    offset_j:
      - 0
      - 0
      - 0
    value:
      - 0.86602540378*Dy
      - 0.5*Dy
      - '-Dz'
    distance: 3.665
  - type: dm_manual
    atom_i: 2
    atom_j: 1
    offset_j:
      - -1
      - 0
      - 0
    value:
      - 0.86602540378*Dy
      - '-0.5*Dy'
      - Dz
    distance: 3.665
  - type: dm_manual
    atom_i: 2
    atom_j: 0
    offset_j:
      - 0
      - 1
      - 0
    value:
      - 0.86602540378*Dy
      - 0.5*Dy
      - '-Dz'
    distance: 3.665
  - type: dm_manual
    atom_i: 2
    atom_j: 1
    offset_j:
      - 0
      - 1
      - 0
    value:
      - 0.86602540378*Dy
      - '-0.5*Dy'
      - Dz
    distance: 3.665
parameters:
  S: 2.5
  H_mag: 0
  H_dir:
    - 0
    - 0
    - 1
  J1: 3.23
  J2: 0.11
  Dy: 0.218
  Dz: -0.195
tasks:
  minimization: true
  dispersion: true
  sqw_map: true
q_path:
  Gamma:
    - 0
    - 0
    - 0
  M:
    - 0.5
    - 0
    - 0
  K:
    - 0.333
    - 0.333
    - 0
  path:
    - Gamma
    - M
    - K
    - Gamma
  points_per_segment: 100
minimization:
  enabled: false
  num_starts: 1000
  n_workers: 8
  early_stopping: 10
  method: L-BFGS-B
plotting:
  energy_min: 0
  energy_max: 10
  broadening: 0.2
  energy_resolution: 0.05
  momentum_max: 4
  save_plot: true
  energy_limits_disp:
    - 0
    - 10
  broadening_width: 0.2

calculation:
  cache_mode: none
output:
  export_csv: false