crystal_structure:
  lattice_vectors:
  - - 7.33
    - 0.0
    - 0.0
  - - -3.6649999999999987
    - 6.347966209739936
    - 0.0
  - - 1.0493631027853925e-15
    - 1.8175502096124213e-15
    - 17.1374
  dimensionality: 2
  magnetic_elements:
  - Fe
  atoms_uc:
  - label: Fe0
    pos:
    - 0.5
    - 0.0
    - 0.0
    spin_S: 2.5
  - label: Fe1
    pos:
    - 0.5
    - 0.5
    - 0.0
    spin_S: 2.5
  - label: Fe2
    pos:
    - 0.0
    - 0.5
    - 0.0
    spin_S: 2.5
calculation:
  cache_mode: w
  cache_file_base: KFe3J_pure_cache
interactions:
- type: heisenberg
  pair:
  - Fe0
  - Fe1
  rij_offset:
  - 0
  - -1
  - 0
  value: J1
  distance: 3.665
- type: heisenberg
  pair:
  - Fe1
  - Fe0
  rij_offset:
  - 0
  - 1
  - 0
  value: J1
  distance: 3.665
- type: heisenberg
  pair:
  - Fe0
  - Fe1
  rij_offset:
  - 0
  - 0
  - 0
  value: J1
  distance: 3.665
- type: heisenberg
  pair:
  - Fe1
  - Fe0
  rij_offset:
  - 0
  - 0
  - 0
  value: J1
  distance: 3.665
- type: heisenberg
  pair:
  - Fe1
  - Fe2
  rij_offset:
  - 1
  - 0
  - 0
  value: J1
  distance: 3.665
- type: heisenberg
  pair:
  - Fe2
  - Fe1
  rij_offset:
  - -1
  - 0
  - 0
  value: J1
  distance: 3.665
- type: heisenberg
  pair:
  - Fe1
  - Fe2
  rij_offset:
  - 0
  - 0
  - 0
  value: J1
  distance: 3.665
- type: heisenberg
  pair:
  - Fe2
  - Fe1
  rij_offset:
  - 0
  - 0
  - 0
  value: J1
  distance: 3.665
- type: heisenberg
  pair:
  - Fe2
  - Fe0
  rij_offset:
  - 0
  - 1
  - 0
  value: J1
  distance: 3.665
- type: heisenberg
  pair:
  - Fe0
  - Fe2
  rij_offset:
  - 0
  - -1
  - 0
  value: J1
  distance: 3.665
- type: heisenberg
  pair:
  - Fe2
  - Fe0
  rij_offset:
  - -1
  - 0
  - 0
  value: J1
  distance: 3.665
- type: heisenberg
  pair:
  - Fe0
  - Fe2
  rij_offset:
  - 1
  - 0
  - 0
  value: J1
  distance: 3.665
- type: heisenberg
  pair:
  - Fe0
  - Fe2
  rij_offset:
  - 0
  - 0
  - 0
  value: J2
  distance: 6.348
- type: heisenberg
  pair:
  - Fe2
  - Fe0
  rij_offset:
  - 0
  - 0
  - 0
  value: J2
  distance: 6.348
- type: heisenberg
  pair:
  - Fe0
  - Fe2
  rij_offset:
  - 1
  - -1
  - 0
  value: J2
  distance: 6.348
- type: heisenberg
  pair:
  - Fe2
  - Fe0
  rij_offset:
  - -1
  - 1
  - 0
  value: J2
  distance: 6.348
- type: heisenberg
  pair:
  - Fe1
  - Fe0
  rij_offset:
  - -1
  - 0
  - 0
  value: J2
  distance: 6.348
- type: heisenberg
  pair:
  - Fe0
  - Fe1
  rij_offset:
  - 1
  - 0
  - 0
  value: J2
  distance: 6.348
- type: heisenberg
  pair:
  - Fe1
  - Fe0
  rij_offset:
  - 1
  - 1
  - 0
  value: J2
  distance: 6.348
- type: heisenberg
  pair:
  - Fe0
  - Fe1
  rij_offset:
  - -1
  - -1
  - 0
  value: J2
  distance: 6.348
- type: heisenberg
  pair:
  - Fe2
  - Fe1
  rij_offset:
  - -1
  - -1
  - 0
  value: J2
  distance: 6.348
- type: heisenberg
  pair:
  - Fe1
  - Fe2
  rij_offset:
  - 1
  - 1
  - 0
  value: J2
  distance: 6.348
- type: heisenberg
  pair:
  - Fe2
  - Fe1
  rij_offset:
  - 0
  - 1
  - 0
  value: J2
  distance: 6.348
- type: heisenberg
  pair:
  - Fe1
  - Fe2
  rij_offset:
  - 0
  - -1
  - 0
  value: J2
  distance: 6.348
- type: dm_manual
  pair:
  - Fe2
  - Fe1
  atom_i: 2
  atom_j: 1
  offset_j:
  - -1
  - 0
  - 0
  rij_offset:
  - -1
  - 0
  - 0
  value:
  - -2.80376405998579e-17*Dy + 1.6103277430163e-33*Dz
  - 1.0*Dy + 2.41435584397759e-33*Dz
  - 1.0*Dz
  distance: 3.665
- type: dm_manual
  pair:
  - Fe1
  - Fe2
  atom_i: 1
  atom_j: 2
  offset_j:
  - 1
  - 0
  - 0
  rij_offset:
  - 1
  - 0
  - 0
  value:
  - 2.80376405998579e-17*Dy - 1.6103277430163e-33*Dz
  - -1.0*Dy - 2.41435584397759e-33*Dz
  - -1.0*Dz
  distance: 3.665
- type: dm_manual
  pair:
  - Fe2
  - Fe1
  atom_i: 2
  atom_j: 1
  offset_j:
  - 0
  - 0
  - 0
  rij_offset:
  - 0
  - 0
  - 0
  value:
  - -2.80376405998579e-17*Dy + 1.6103277430163e-33*Dz
  - 1.0*Dy + 2.41435584397759e-33*Dz
  - 1.0*Dz
  distance: 3.665
- type: dm_manual
  pair:
  - Fe1
  - Fe2
  atom_i: 1
  atom_j: 2
  offset_j:
  - 0
  - 0
  - 0
  rij_offset:
  - 0
  - 0
  - 0
  value:
  - 2.80376405998579e-17*Dy - 1.6103277430163e-33*Dz
  - -1.0*Dy - 2.41435584397759e-33*Dz
  - -1.0*Dz
  distance: 3.665
- type: dm_manual
  pair:
  - Fe0
  - Fe2
  atom_i: 0
  atom_j: 2
  offset_j:
  - 0
  - -1
  - 0
  rij_offset:
  - 0
  - -1
  - 0
  value:
  - -0.866025403784439*Dy + 1.22464679914735e-16*Dz
  - 0.5*Dy + 2.41435584397759e-33*Dz
  - 1.0*Dz
  distance: 3.665
- type: dm_manual
  pair:
  - Fe2
  - Fe0
  atom_i: 2
  atom_j: 0
  offset_j:
  - 0
  - 1
  - 0
  rij_offset:
  - 0
  - 1
  - 0
  value:
  - 0.866025403784439*Dy - 1.22464679914735e-16*Dz
  - -0.5*Dy - 2.41435584397759e-33*Dz
  - -1.0*Dz
  distance: 3.665
- type: dm_manual
  pair:
  - Fe0
  - Fe2
  atom_i: 0
  atom_j: 2
  offset_j:
  - 1
  - 0
  - 0
  rij_offset:
  - 1
  - 0
  - 0
  value:
  - -0.866025403784439*Dy + 1.22464679914735e-16*Dz
  - 0.5*Dy + 2.41435584397759e-33*Dz
  - 1.0*Dz
  distance: 3.665
- type: dm_manual
  pair:
  - Fe2
  - Fe0
  atom_i: 2
  atom_j: 0
  offset_j:
  - -1
  - 0
  - 0
  rij_offset:
  - -1
  - 0
  - 0
  value:
  - 0.866025403784439*Dy - 1.22464679914735e-16*Dz
  - -0.5*Dy - 2.41435584397759e-33*Dz
  - -1.0*Dz
  distance: 3.665
- type: dm_manual
  pair:
  - Fe1
  - Fe0
  atom_i: 1
  atom_j: 0
  offset_j:
  - 0
  - 0
  - 0
  rij_offset:
  - 0
  - 0
  - 0
  value:
  - -0.866025403784439*Dy + 1.83697019872103e-16*Dz
  - -0.5*Dy + 1.06057523872491e-16*Dz
  - 1.0*Dz
  distance: 3.665
- type: dm_manual
  pair:
  - Fe0
  - Fe1
  atom_i: 0
  atom_j: 1
  offset_j:
  - 0
  - 0
  - 0
  rij_offset:
  - 0
  - 0
  - 0
  value:
  - 0.866025403784439*Dy - 1.83697019872103e-16*Dz
  - 0.5*Dy - 1.06057523872491e-16*Dz
  - -1.0*Dz
  distance: 3.665
- type: dm_manual
  pair:
  - Fe1
  - Fe0
  atom_i: 1
  atom_j: 0
  offset_j:
  - 0
  - 1
  - 0
  rij_offset:
  - 0
  - 1
  - 0
  value:
  - -0.866025403784439*Dy + 1.83697019872103e-16*Dz
  - -0.5*Dy + 1.06057523872491e-16*Dz
  - 1.0*Dz
  distance: 3.665
- type: dm_manual
  pair:
  - Fe0
  - Fe1
  atom_i: 0
  atom_j: 1
  offset_j:
  - 0
  - -1
  - 0
  rij_offset:
  - 0
  - -1
  - 0
  value:
  - 0.866025403784439*Dy - 1.83697019872103e-16*Dz
  - 0.5*Dy - 1.06057523872491e-16*Dz
  - -1.0*Dz
  distance: 3.665
parameters:
  S: 2.5
  J1: 3.23
  J2: 0.11
  Dy: 0.218
  Dz: -0.195
  H_dir:
  - 0.0
  - 0.0
  - 1.0
  H_mag: 0.0
minimization:
  enabled: true
  method: L-BFGS-B
  maxiter: 5000
  initial_configuration:
  - atom_index: 0
    phi: 5.235987755982989
  - atom_index: 1
    phi: 3.141592653589793
  - atom_index: 2
    phi: 1.0471975511965976
q_path:
  G:
  - 0.0
  - 0.0
  - 0.0
  K:
  - 0.333333
  - 0.333333
  - 0.0
  M:
  - 0.5
  - 0.0
  - 0.0
  path:
  - G
  - K
  - M
  - G
  points_per_segment: 200
output:
  disp_data_filename: "KFe3J_pure_disp.npz"
  sqw_data_filename: "KFe3J_pure_sqw.npz"
plotting:
  save_plot: true
  disp_plot_filename: "KFe3J_pure_disp.png"
  sqw_plot_filename: "KFe3J_pure_sqw.png"
  show_plot: false
  energy_limits_disp:
  - 0
  - 20
  energy_limits_sqw:
  - 0
  - 20
  plot_structure: false
tasks:
  run_minimization: true
  run_dispersion: true
  plot_dispersion: true
  run_sqw_map: true
  plot_sqw_map: true
parameter_order:
- J1
- J2
- Dy
- Dz
- H_dir
- H_mag

calculation:
  cache_mode: none
output:
  export_csv: false