crystal_structure:
  lattice_parameters:
    a: 7.33
    b: 7.33
    c: 17.1374
    alpha: 90
    beta: 90
    gamma: 120
  atoms_uc:
    - label: Fe0
      pos: [0.5, 0, 0]
      spin_S: 2.5
    - label: Fe1
      pos: [0, 0.5, 0]
      spin_S: 2.5
    - label: Fe2
      pos: [0.5, 0.5, 0]
      spin_S: 2.5
    - label: Fe3
      pos: [0, 0.5, 0.5]
      spin_S: 2.5
    - label: Fe4
      pos: [0.5, 0, 0.5]
      spin_S: 2.5
    - label: Fe5
      pos: [0.5, 0.5, 0.5]
      spin_S: 2.5
  magnetic_elements:
    - Cu
  dimensionality: 2
interactions:
  - type: heisenberg
    pair: [Fe1, Fe2]
    rij_offset: [0, 0, 0]
    value: J1
    distance: 3.665
  - type: heisenberg
    pair: [Fe2, Fe1]
    rij_offset: [0, 0, 0]
    value: J1
    distance: 3.665
  - type: heisenberg
    pair: [Fe1, Fe2]
    rij_offset: [-1, 0, 0]
    value: J1
    distance: 3.665
  - type: heisenberg
    pair: [Fe2, Fe1]
    rij_offset: [1, 0, 0]
    value: J1
    distance: 3.665
  - type: heisenberg
    pair: [Fe0, Fe1]
    rij_offset: [1, 0, 0]
    value: J1
    distance: 3.665
  - type: heisenberg
    pair: [Fe1, Fe0]
    rij_offset: [-1, 0, 0]
    value: J1
    distance: 3.665
  - type: heisenberg
    pair: [Fe0, Fe1]
    rij_offset: [0, -1, 0]
    value: J1
    distance: 3.665
  - type: heisenberg
    pair: [Fe1, Fe0]
    rij_offset: [0, 1, 0]
    value: J1
    distance: 3.665
  - type: heisenberg
    pair: [Fe2, Fe0]
    rij_offset: [0, 1, 0]
    value: J1
    distance: 3.665
  - type: heisenberg
    pair: [Fe0, Fe2]
    rij_offset: [0, -1, 0]
    value: J1
    distance: 3.665
  - type: heisenberg
    pair: [Fe2, Fe0]
    rij_offset: [0, 0, 0]
    value: J1
    distance: 3.665
  - type: heisenberg
    pair: [Fe0, Fe2]
    rij_offset: [0, 0, 0]
    value: J1
    distance: 3.665
  - type: heisenberg
    pair: [Fe3, Fe5]
    rij_offset: [0, 0, 0]
    value: J1
    distance: 3.665
  - type: heisenberg
    pair: [Fe5, Fe3]
    rij_offset: [0, 0, 0]
    value: J1
    distance: 3.665
  - type: heisenberg
    pair: [Fe3, Fe5]
    rij_offset: [-1, 0, 0]
    value: J1
    distance: 3.665
  - type: heisenberg
    pair: [Fe5, Fe3]
    rij_offset: [1, 0, 0]
    value: J1
    distance: 3.665
  - type: heisenberg
    pair: [Fe4, Fe3]
    rij_offset: [1, 0, 0]
    value: J1
    distance: 3.665
  - type: heisenberg
    pair: [Fe3, Fe4]
    rij_offset: [-1, 0, 0]
    value: J1
    distance: 3.665
  - type: heisenberg
    pair: [Fe4, Fe3]
    rij_offset: [0, -1, 0]
    value: J1
    distance: 3.665
  - type: heisenberg
    pair: [Fe3, Fe4]
    rij_offset: [0, 1, 0]
    value: J1
    distance: 3.665
  - type: heisenberg
    pair: [Fe5, Fe4]
    rij_offset: [0, 1, 0]
    value: J1
    distance: 3.665
  - type: heisenberg
    pair: [Fe4, Fe5]
    rij_offset: [0, -1, 0]
    value: J1
    distance: 3.665
  - type: heisenberg
    pair: [Fe5, Fe4]
    rij_offset: [0, 0, 0]
    value: J1
    distance: 3.665
  - type: heisenberg
    pair: [Fe4, Fe5]
    rij_offset: [0, 0, 0]
    value: J1
    distance: 3.665
  - type: heisenberg
    pair: [Fe0, Fe1]
    rij_offset: [0, 0, 0]
    value: J2
    distance: 6.347966209739935
  - type: heisenberg
    pair: [Fe1, Fe0]
    rij_offset: [0, 0, 0]
    value: J2
    distance: 6.347966209739935
  - type: heisenberg
    pair: [Fe0, Fe1]
    rij_offset: [1, -1, 0]
    value: J2
    distance: 6.347966209739935
  - type: heisenberg
    pair: [Fe1, Fe0]
    rij_offset: [-1, 1, 0]
    value: J2
    distance: 6.347966209739935
  - type: heisenberg
    pair: [Fe2, Fe0]
    rij_offset: [-1, 0, 0]
    value: J2
    distance: 6.347966209739935
  - type: heisenberg
    pair: [Fe0, Fe2]
    rij_offset: [1, 0, 0]
    value: J2
    distance: 6.347966209739935
  - type: heisenberg
    pair: [Fe2, Fe0]
    rij_offset: [1, 1, 0]
    value: J2
    distance: 6.347966209739935
  - type: heisenberg
    pair: [Fe0, Fe2]
    rij_offset: [-1, -1, 0]
    value: J2
    distance: 6.347966209739935
  - type: heisenberg
    pair: [Fe1, Fe2]
    rij_offset: [-1, -1, 0]
    value: J2
    distance: 6.347966209739935
  - type: heisenberg
    pair: [Fe2, Fe1]
    rij_offset: [1, 1, 0]
    value: J2
    distance: 6.347966209739935
  - type: heisenberg
    pair: [Fe1, Fe2]
    rij_offset: [0, 1, 0]
    value: J2
    distance: 6.347966209739935
  - type: heisenberg
    pair: [Fe2, Fe1]
    rij_offset: [0, -1, 0]
    value: J2
    distance: 6.347966209739935
  - type: heisenberg
    pair: [Fe4, Fe3]
    rij_offset: [0, 0, 0]
    value: J2
    distance: 6.347966209739935
  - type: heisenberg
    pair: [Fe3, Fe4]
    rij_offset: [0, 0, 0]
    value: J2
    distance: 6.347966209739935
  - type: heisenberg
    pair: [Fe4, Fe3]
    rij_offset: [1, -1, 0]
    value: J2
    distance: 6.347966209739935
  - type: heisenberg
    pair: [Fe3, Fe4]
    rij_offset: [-1, 1, 0]
    value: J2
    distance: 6.347966209739935
  - type: heisenberg
    pair: [Fe5, Fe4]
    rij_offset: [-1, 0, 0]
    value: J2
    distance: 6.347966209739935
  - type: heisenberg
    pair: [Fe4, Fe5]
    rij_offset: [1, 0, 0]
    value: J2
    distance: 6.347966209739935
  - type: heisenberg
    pair: [Fe5, Fe4]
    rij_offset: [1, 1, 0]
    value: J2
    distance: 6.347966209739935
  - type: heisenberg
    pair: [Fe4, Fe5]
    rij_offset: [-1, -1, 0]
    value: J2
    distance: 6.347966209739935
  - type: heisenberg
    pair: [Fe3, Fe5]
    rij_offset: [-1, -1, 0]
    value: J2
    distance: 6.347966209739935
  - type: heisenberg
    pair: [Fe5, Fe3]
    rij_offset: [1, 1, 0]
    value: J2
    distance: 6.347966209739935
  - type: heisenberg
    pair: [Fe3, Fe5]
    rij_offset: [0, 1, 0]
    value: J2
    distance: 6.347966209739935
  - type: heisenberg
    pair: [Fe5, Fe3]
    rij_offset: [0, -1, 0]
    value: J2
    distance: 6.347966209739935
  - type: dm_manual
    pair: [Fe1, Fe2]
    atom_i: 1
    atom_j: 2
    offset_j: [0, 0, 0]
    rij_offset: [0, 0, 0]
    value: ['-2.80376405998579e-17*Dy + 1.6103277430163e-33*Dz', 1.0*Dy + 2.41435584397759e-33*Dz, 1.0*Dz]
    distance: 3.665
  - type: dm_manual
    pair: [Fe2, Fe1]
    atom_i: 2
    atom_j: 1
    offset_j: [0, 0, 0]
    rij_offset: [0, 0, 0]
    value: [2.80376405998579e-17*Dy - 1.6103277430163e-33*Dz, '-1.0*Dy - 2.41435584397759e-33*Dz', '-1.0*Dz']
    distance: 3.665
  - type: dm_manual
    pair: [Fe1, Fe2]
    atom_i: 1
    atom_j: 2
    offset_j: [-1, 0, 0]
    rij_offset: [-1, 0, 0]
    value: ['-2.80376405998579e-17*Dy + 1.6103277430163e-33*Dz', 1.0*Dy + 2.41435584397759e-33*Dz, 1.0*Dz]
    distance: 3.665
  - type: dm_manual
    pair: [Fe2, Fe1]
    atom_i: 2
    atom_j: 1
    offset_j: [1, 0, 0]
    rij_offset: [1, 0, 0]
    value: [2.80376405998579e-17*Dy - 1.6103277430163e-33*Dz, '-1.0*Dy - 2.41435584397759e-33*Dz', '-1.0*Dz']
    distance: 3.665
  - type: dm_manual
    pair: [Fe0, Fe1]
    atom_i: 0
    atom_j: 1
    offset_j: [1, 0, 0]
    rij_offset: [1, 0, 0]
    value: ['-0.866025403784439*Dy + 1.22464679914735e-16*Dz', 0.5*Dy + 2.41435584397759e-33*Dz, 1.0*Dz]
    distance: 3.665
  - type: dm_manual
    pair: [Fe1, Fe0]
    atom_i: 1
    atom_j: 0
    offset_j: [-1, 0, 0]
    rij_offset: [-1, 0, 0]
    value: [0.866025403784439*Dy - 1.22464679914735e-16*Dz, '-0.5*Dy - 2.41435584397759e-33*Dz', '-1.0*Dz']
    distance: 3.665
  - type: dm_manual
    pair: [Fe0, Fe1]
    atom_i: 0
    atom_j: 1
    offset_j: [0, -1, 0]
    rij_offset: [0, -1, 0]
    value: ['-0.866025403784439*Dy + 1.22464679914735e-16*Dz', 0.5*Dy + 2.41435584397759e-33*Dz, 1.0*Dz]
    distance: 3.665
  - type: dm_manual
    pair: [Fe1, Fe0]
    atom_i: 1
    atom_j: 0
    offset_j: [0, 1, 0]
    rij_offset: [0, 1, 0]
    value: [0.866025403784439*Dy - 1.22464679914735e-16*Dz, '-0.5*Dy - 2.41435584397759e-33*Dz', '-1.0*Dz']
    distance: 3.665
  - type: dm_manual
    pair: [Fe2, Fe0]
    atom_i: 2
    atom_j: 0
    offset_j: [0, 1, 0]
    rij_offset: [0, 1, 0]
    value: ['-0.866025403784439*Dy + 1.83697019872103e-16*Dz', '-0.5*Dy + 1.06057523872491e-16*Dz', 1.0*Dz]
    distance: 3.665
  - type: dm_manual
    pair: [Fe0, Fe2]
    atom_i: 0
    atom_j: 2
    offset_j: [0, -1, 0]
    rij_offset: [0, -1, 0]
    value: [0.866025403784439*Dy - 1.83697019872103e-16*Dz, 0.5*Dy - 1.06057523872491e-16*Dz, '-1.0*Dz']
    distance: 3.665
  - type: dm_manual
    pair: [Fe2, Fe0]
    atom_i: 2
    atom_j: 0
    offset_j: [0, 0, 0]
    rij_offset: [0, 0, 0]
    value: ['-0.866025403784439*Dy + 1.83697019872103e-16*Dz', '-0.5*Dy + 1.06057523872491e-16*Dz', 1.0*Dz]
    distance: 3.665
  - type: dm_manual
    pair: [Fe0, Fe2]
    atom_i: 0
    atom_j: 2
    offset_j: [0, 0, 0]
    rij_offset: [0, 0, 0]
    value: [0.866025403784439*Dy - 1.83697019872103e-16*Dz, 0.5*Dy - 1.06057523872491e-16*Dz, '-1.0*Dz']
    distance: 3.665
  - type: dm_manual
    pair: [Fe3, Fe5]
    atom_i: 3
    atom_j: 5
    offset_j: [0, 0, 0]
    rij_offset: [0, 0, 0]
    value: ['-2.80376405998579e-17*Dy + 1.6103277430163e-33*Dz', 1.0*Dy + 2.41435584397759e-33*Dz, 1.0*Dz]
    distance: 3.665
  - type: dm_manual
    pair: [Fe5, Fe3]
    atom_i: 5
    atom_j: 3
    offset_j: [0, 0, 0]
    rij_offset: [0, 0, 0]
    value: [2.80376405998579e-17*Dy - 1.6103277430163e-33*Dz, '-1.0*Dy - 2.41435584397759e-33*Dz', '-1.0*Dz']
    distance: 3.665
  - type: dm_manual
    pair: [Fe3, Fe5]
    atom_i: 3
    atom_j: 5
    offset_j: [-1, 0, 0]
    rij_offset: [-1, 0, 0]
    value: ['-2.80376405998579e-17*Dy + 1.6103277430163e-33*Dz', 1.0*Dy + 2.41435584397759e-33*Dz, 1.0*Dz]
    distance: 3.665
  - type: dm_manual
    pair: [Fe5, Fe3]
    atom_i: 5
    atom_j: 3
    offset_j: [1, 0, 0]
    rij_offset: [1, 0, 0]
    value: [2.80376405998579e-17*Dy - 1.6103277430163e-33*Dz, '-1.0*Dy - 2.41435584397759e-33*Dz', '-1.0*Dz']
    distance: 3.665
  - type: dm_manual
    pair: [Fe4, Fe3]
    atom_i: 4
    atom_j: 3
    offset_j: [1, 0, 0]
    rij_offset: [1, 0, 0]
    value: ['-0.866025403784439*Dy + 1.22464679914735e-16*Dz', 0.5*Dy + 2.41435584397759e-33*Dz, 1.0*Dz]
    distance: 3.665
  - type: dm_manual
    pair: [Fe3, Fe4]
    atom_i: 3
    atom_j: 4
    offset_j: [-1, 0, 0]
    rij_offset: [-1, 0, 0]
    value: [0.866025403784439*Dy - 1.22464679914735e-16*Dz, '-0.5*Dy - 2.41435584397759e-33*Dz', '-1.0*Dz']
    distance: 3.665
  - type: dm_manual
    pair: [Fe4, Fe3]
    atom_i: 4
    atom_j: 3
    offset_j: [0, -1, 0]
    rij_offset: [0, -1, 0]
    value: ['-0.866025403784439*Dy + 1.22464679914735e-16*Dz', 0.5*Dy + 2.41435584397759e-33*Dz, 1.0*Dz]
    distance: 3.665
  - type: dm_manual
    pair: [Fe3, Fe4]
    atom_i: 3
    atom_j: 4
    offset_j: [0, 1, 0]
    rij_offset: [0, 1, 0]
    value: [0.866025403784439*Dy - 1.22464679914735e-16*Dz, '-0.5*Dy - 2.41435584397759e-33*Dz', '-1.0*Dz']
    distance: 3.665
  - type: dm_manual
    pair: [Fe5, Fe4]
    atom_i: 5
    atom_j: 4
    offset_j: [0, 1, 0]
    rij_offset: [0, 1, 0]
    value: ['-0.866025403784439*Dy + 1.83697019872103e-16*Dz', '-0.5*Dy + 1.06057523872491e-16*Dz', 1.0*Dz]
    distance: 3.665
  - type: dm_manual
    pair: [Fe4, Fe5]
    atom_i: 4
    atom_j: 5
    offset_j: [0, -1, 0]
    rij_offset: [0, -1, 0]
    value: [0.866025403784439*Dy - 1.83697019872103e-16*Dz, 0.5*Dy - 1.06057523872491e-16*Dz, '-1.0*Dz']
    distance: 3.665
  - type: dm_manual
    pair: [Fe5, Fe4]
    atom_i: 5
    atom_j: 4
    offset_j: [0, 0, 0]
    rij_offset: [0, 0, 0]
    value: ['-0.866025403784439*Dy + 1.83697019872103e-16*Dz', '-0.5*Dy + 1.06057523872491e-16*Dz', 1.0*Dz]
    distance: 3.665
  - type: dm_manual
    pair: [Fe4, Fe5]
    atom_i: 4
    atom_j: 5
    offset_j: [0, 0, 0]
    rij_offset: [0, 0, 0]
    value: [0.866025403784439*Dy - 1.83697019872103e-16*Dz, 0.5*Dy - 1.06057523872491e-16*Dz, '-1.0*Dz']
    distance: 3.665
parameters:
  J1: 3.23
  J2: 0.11
  Dy: -0.218
  Dz: 0.195
  H_dir: [0, 0, 1]
  H_mag: 0
tasks:
  run_minimization: true
  run_dispersion: true
  calculate_dispersion_new: true
  plot_dispersion: true
  run_sqw_map: true
  calculate_sqw_map_new: true
  plot_sqw_map: true
  export_csv: false
q_path:
  Gamma: [0, 0, 0]
  M: [0.5, 0, 0]
  K: [0.333, 0.333, 0]
  path: [Gamma, M, K, Gamma]
  points_per_segment: 100
minimization:
  enabled: true
  num_starts: 1000
  n_workers: 8
  early_stopping: 10
  method: L-BFGS-B
plotting:
  energy_min: 0
  energy_max: 20
  broadening: 0.2
  energy_resolution: 0.05
  momentum_max: 4
  save_plot: false
  show_plot: false
  plot_structure: false
  energy_limits_disp: [0, 20]
  broadening_width: 0.2
calculation:
  cache_mode: none
output:
  disp_csv_filename: disp_data.csv
  sqw_csv_filename: sqw_data.csv
