crystal_structure:
  lattice_parameters:
    a: 7.33009
    b: 7.33009
    c: 17.1374
    alpha: 90
    beta: 90
    gamma: 120.00000000000001
    space_group: 166
  wyckoff_atoms:
    - label: Fe
      pos: [0.16667, 0.83333, 0.83333]
      spin_S: 2.5
      species: Fe
  atom_mode: symmetry
  magnetic_elements:
    - Fe
interactions:
  symmetry_rules:
    - type: heisenberg
      distance: 3.664971699100001
      value: J1
      ref_pair: &ref_0
        - Fe1
        - Fe5
      offset: &ref_1
        - 0
        - 0
        - 0
    - type: dm
      distance: 3.664971699100001
      value: 0,Dy,-Dz
      ref_pair: *ref_0
      offset: *ref_1
    - type: heisenberg
      distance: 6.3480441520732995
      value: J2
      ref_pair: [Fe0, Fe2]
      offset: [-1, 0, 0]
parameters:
  S: 1
  H_mag: 0
  H_dir: [0, 0, 1]
  J1: 3.23
  J2: 0.11
  Dy: 0.218
  Dz: -0.195
tasks:
  minimization: true
  dispersion: true
  sqw_map: true
  export_csv: false
q_path:
  Gamma: [0, 0, 0]
  M: [0.5, 0, 0]
  K: [0.333, 0.333, 0]
  path: [Gamma, M, K, Gamma]
  points_per_segment: 100
plotting:
  energy_min: 0
  energy_max: 20
  broadening: 0.2
  energy_resolution: 0.05
  momentum_max: 4
  save_plot: false
  disp_plot_filename: disp_plot.png
  sqw_plot_filename: sqw_plot.png
  show_plot: false
  plot_structure: false
  energy_limits_disp: [0, 20]
  broadening_width: 0.2
minimization:
  enabled: true
  num_starts: 1000
  n_workers: 8
  early_stopping: 10
  method: L-BFGS-B
output:
  disp_data_filename: disp_data.npz
  sqw_data_filename: sqw_data.npz
  disp_csv_filename: disp_data.csv
  sqw_csv_filename: sqw_data.csv
  save_data: false
